### ISSUE TITLE
CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by ranfysvalle02** [mongodb-developer/GenAI-Showcase#52]
<img width="1166" alt="Screenshot 2024-12-06 at 10 30 19 PM" src="https://github.com/user-attachments/assets/630003e7-0198-49c5-b4f1-cd64a567b1e1">

**Comment by ajosh0504** [comment]
@ranfysvalle02 Can you elaborate on the issue?

**Comment by ajosh0504** [comment]
Added basic contribution guidelines in the PR linked above.
